spring:
  application:
    name: jpbbackend
  datasource:
    username: tu
    password: hello
    url: jdbc:mysql://localhost:3306/products?allowPublicKeyRetrieval=true&useSSL=true
server:
  port: 8111